title:            Lingfeng's Blog
description:      101s and notes for dummies just like me.
#logo:             site-logo.jpg
disqus_shortname:
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://hanxiaomax.github.io

# Owner/author information
owner:
  name:           Lingfeng Ai
  avatar:         bio-photo.jpg
  email:          hanxiaomax@qq.com
  # Social networking links used in footer. Update and remove as you like.
  github:         hanxiaomax

comments:
  provider: custom

# Analytics and webmaster tools stuff goes here
analytics :
  provider : google
  google :
      tracking_id : 'UA-48815860-1'
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: tags
    url: /tags/
  - title: Articles
    url: /articles/
  - title: Python
    url: /Python/
  - title: Etymology
    url: /etymology/
  - title: C/C++
    url: /cpp/
  - title: 技术翻译
    url: /translate/
  - title: other
    url: /other/
  - title: Fist
    url: /fist/
  - title: 新浪微博
    url: http://weibo.com/smilingly1989
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Chongqing
future:      true
highlighter: pygments
markdown:    redcarpet



# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/


redcarpet:
  extensions: ['fenced_code_blocks','tables','strikethrough','no_intra_emphasis']


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
